# fly.toml app configuration file generated for movie-web on 2024-03-21T08:51:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'movie-web'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
